//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public int address_id { get; set; }
        public string address_name { get; set; }
        public Nullable<decimal> address_latitude { get; set; }
        public Nullable<decimal> address_longitude { get; set; }
        public string address_description { get; set; }
        public bool address_active { get; set; }
        public int user_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
