//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cards()
        {
            this.Collections = new HashSet<Collections>();
        }
    
        public int card_id { get; set; }
        public string card_payday { get; set; }
        public int card_payment_amount { get; set; }
        public string card_item { get; set; }
        public bool card_state { get; set; }
        public bool card_active { get; set; }
        public int user_id { get; set; }
        public int frequency_id { get; set; }
        public Nullable<int> item_id { get; set; }
    
        public virtual Frequencies Frequencies { get; set; }
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collections> Collections { get; set; }
    }
}
