//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestionVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collections
    {
        public int collection_id { get; set; }
        public System.DateTime collection_date { get; set; }
        public int collection_amount { get; set; }
        public int collection_balance { get; set; }
        public string collection_note { get; set; }
        public bool collection_active { get; set; }
        public int user_id { get; set; }
        public int card_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Cards Cards { get; set; }
    }
}
